### PR TITLE
Extend Illuminate Controller instead of App Controller

### PR DESCRIPTION
**Pull request by gassius**
Extend Illuminate\Routing\Controller instead the App Controller in the RecaptchaController.

This adheres to best practices and allows the use of the Add On in Applications where App is not the root namespace

### CODE REVIEW

**Review by anakadote — CHANGES_REQUESTED** [review]
I'm not opposed to this, but I'd prefer not aliasing the controller class. If you change `BaseController` to simply `Controller` I'll approved this PR.

**Comment by gassius** [comment]
@anakadote Agree, the alias is not needed. requested change applied to this PR now

**Review by anakadote — CHANGES_REQUESTED** [review]
Just need to fix the ordering of the imports now (they should be ordered alphabetically)/

**Comment by gassius** [comment]
> Just need to fix the ordering of the imports now (they should be ordered alphabetically)/

Done

**Pull request merged**
